### PR TITLE
feat(router): redirect with token parameters

### PR DESCRIPTION
**Pull request by jagonalez**
allow redirect to contain token parameters for router config

this closes feature request #483

### CODE REVIEW

**Comment by djensen47** [comment]
Any updates on this? Would be really nice to have.

**Comment by EisenbergEffect** [comment]
@davismj Can you review this? It looks like an interesting feature.

**Comment by davismj** [comment]
@jagonalez Sorry for the wait. Sincerely appreciate your hard work as always.

@djensen47 Thanks for your patience. Merged!

**Comment by Alexander-Taran** [comment]
@jagonalez would you mind creating another PR for docs?
Or explain a bit on how it works.. so we could update the docs with a use case?

**Comment by huochunpeng** [comment]
@jagonalez @davismj @EisenbergEffect 

This new design of redirect disabled the old usage of redirect as in #607
It also causes regression in #605

This looks like a very isolated change, can we revert this commit for now?

Need to revise the design and add test coverage to ensure not breaking #605 and #607.

**Pull request merged**
