### PR TITLE
fix(activation): Deactivate child viewModels when replacing a parent 

### LINKED ISSUE #132: Deactivate method isn't called when user is moving between two child routers.
I think that deactivate method isn't called on page for this situation:
- application has 3 routers defined as one master router with two child routers
- user moves from page in one child router to different page in different child router and deactivate method on page where user was at the begining isn't called.

Example of how child routers are configured:

**app.js**:

```
config.map([
  { route: '',  moduleId: './welcome',      nav: true, title:'Welcome' },
    { route: 'child1', moduleId: './child1', nav: true, title: 'Child 1' },
    { route: 'child2', moduleId: './child2', nav: true, title: 'Child 2' },
  ]);
```

**child1.js**

```
config.map([
  { route: '', moduleId: './page1', nav: true, title:'Page 1' },
  { route: 'page1a', moduleId: './page1a', nav: true, title:'Page 1a' },
]);
```

**child2.js**

```
config.map([
  { route: '', moduleId: './page2', nav: true, title:'Page 2' },
]);
```

When user is on _Page 1a_ and moves to _Page 2_ this is list of called events:
- child1.js - deactivate
- child2.js - activate
- page2.js - activate
- child1.js - detached
- page1a.js - detached
- child2.js - attached
- page2.js - attached

I think that as first method must be called deactivate method on _Page 1a_ and then all methods which are called now.

Demo of this problem: https://github.com/milunka/redirect-activate-problem

### PR DESCRIPTION
**Pull request by davismj**
Closes #132 #411 #496

### CODE REVIEW

**Comment by jmezach** [comment]
Any updates on this? We could really use this fix.

**Comment by davismj** [comment]
@EisenbergEffect I think this is good to be pulled  in.

**Comment by EisenbergEffect** [comment]
@davismj You are in charge of reviewing and merging router and it's related libs now. Just let me know when you are ready for me to make a release and whether or not it's minor or patch.

**Comment by Vheissu** [comment]
@davismj Pulled this down locally and everything looks good from here.

**Comment by EisenbergEffect** [comment]
@davismj Looks like there's a conflict in the tests now. Can you resolve that?

**Comment by davismj** [comment]
I've manually merged this here #511.

**Pull request merged**
