### PR TITLE
feat(router config): ignoreUnknownRoutes option

### PR DESCRIPTION
**Pull request by mgraf1**
Implements the ignoreUnknownRoutes option mentioned in issue https://github.com/aurelia/router/issues/527.

### CODE REVIEW

**Comment by davismj** [comment]
@EisenbergEffect I've done some simple testing and I've found that this doesn't seem to solve the issue it was trying to address. In any case, I think we shouldn't release this until its tested and verified, and I'm looking to get a release of the latest changes out in the next week. Shall I revert this using the GitHub revert feature, or manually in Git?

**Comment by EisenbergEffect** [comment]
GitHub revert is fine.

**Comment by PWKad** [comment]
@davismj https://github.com/aurelia/router/pull/561/files this shows how it should work although that's not a final version, as a note there are a handful of failing specs right now but they were failing before I opened that PR.

**Comment by PWKad** [comment]
In a nutshell if you have pushState enabled you should still be able to create an href that is not swallowed by the router (they all currently are) and instead you should be able to trigger navigation that the router ignores.  I think the existing PR simply swallowed the error but we need to propagate the route up which the PR I linked above addresses but is probably a work in progress, let me know if that makes sense.  Also if we are not releasing until Tuesday please do not revert a commit without giving the author a chance to fix the issue.

**Comment by davismj** [comment]
@EisenbergEffect opened, I'll pull it in

@PWKad its not that I don't want him to finish it, its that I'd rather not rush it, I'd rather have the time to test these things fully before they get pulled in.

That said, please have a look at https://github.com/aurelia/router/issues/428. I think if we take a step back and ask what kind of use cases we need to support we can improve upon the lessons of Durandal. 

My suggestion there was, instead of ignoreUnknownRoutes, which would essentially break mapping unknown routes to a custom 404 page, is having a route configuration that has some sort of pass through flag.

**Comment by pndewit** [comment]
@davismj The changelog of v1.5.0 says it got pulled in. Just checked and it is not, can you remove the entry from the releases changelog?

**Comment by davismj** [comment]
Thanks, done.

**Pull request merged**
