### PR TITLE
feat(router): enable parent chain unknown route handlers

### PR DESCRIPTION
**Pull request by jagonalez**
bubble up the current router parent chain for the first defined unknown route handler if one does not exists on the current router

feature #443

### CODE REVIEW

**Comment by CasiOo** [comment]
Aurelia's `_commitChanges` method is becoming pretty complicated. Maybe the method should be refactored making it more readable and easier to understand?

**Comment by EisenbergEffect** [comment]
@bryanrsmith Any chance to review this and let me know what you think?

**Comment by matik12** [comment]
@bryanrsmith Any info on this enhancement?

**Comment by EisenbergEffect** [comment]
@Vheissu @davismj Can you either of you review this?

**Pull request merged**
