### PR TITLE
Allow route redirect

### LINKED ISSUE #28: Add `redirect` support to the router
Allow the router to recognize `redirect` keys in routes, and perform the redirect action.

Example:

```js
config.map([
  { route: 'blog',      moduleId: './blog/routes/index', nav: true, title: 'Blog' },
  { route: '',          redirect: '/blog' }
]);
```

This would make the empty route `''` actually redirect to `#/blog` (with path changes). This could be added quite early to the router pipeline, to reduce the overhead of having to go through the entire pipeline.

### PR DESCRIPTION
**Pull request by Alxandr**
Fixes #28

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Well, that turned out to be pretty simple didn't it?

**Comment by Alxandr** [comment]
Yeah, wasn't too difficult.

**Comment by EisenbergEffect** [comment]
@Alxandr  I'm going to merge this but I have to amend your commit message myself. Try to follow the commit guidelines for the future. It takes a bit of getting use to, but it's not that difficult. By doing that we can automatically generate our changelog and release notes very easily and track the things that the community wants/needs to know about.

**Comment by EisenbergEffect** [comment]
Merged in.

**Pull request closed without merging**
