### PR TITLE
fix(navigation-instruction): fix the order of delayed swaps.

### LINKED ISSUE #548: Missing parentOverrideContext when a nested child route is loaded at first time
**I'm submitting a bug report**

* **Library Version:**
1.4.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.13

* **Node Version:**
8.9.0

* **NPM Version:**
5.5.1

* **JSPM OR Webpack AND Version**
NA

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
When a nested child route is loaded at first time, the parentOverrideContext is missing.

https://gist.run/?id=24bddb1ca8e502bcac280fbb3368dd30

This demo setup a nested route, two routes at top level, plus two nested routes in one of the top level page.

The top app.js module defined a variable `face` with value ":-)". Due to all components loaded by aurelia-router have access to app.js component through overrideContext chain, the app is able to display the face in every leaf pages.

But there is a problem, when nested page "/two/one" is loaded first time, the face is missing, but if you visit "/two/two" then visit "/two/one" again, the face comes back.

A debug log in `two/one.js` prints bindingContext and overrideContext in `bind()` callback, it reveals the parentOverrideContext was missing when page "/two/one" was loaded first time, it comes back to normal when it was loaded second time.
screen shot 2017-11-06 at 12 50 50 pm

**Expected/desired behavior:**

* **What is the expected behavior?**
The first load of nested child route should have correct parentOverrideContext set.

* **What is the motivation / use case for changing the behavior?**
I was trying to have a fix by looking into router implementation about the bindingContext manipulation during route activation, but could not find where the related code is. I would appreciate someone from Aurelia team could give me some hint, I would like to attempt to fix it.

### PR DESCRIPTION
**Pull request by 3cp**
Previously, when a child route is loaded at first time, the swap() of child router-view is called before the swap() of parent router-view. The result is when binding the inner view, it could not get correct binding scope since its owningView was not bound yet. This fix makes sure the swaps are executed in the right order.

Closes #548, #476

### CODE REVIEW

**Comment by huochunpeng** [comment]
I am not sure how to write the test code to cover this issue, would appreciate some help.
I tested it against my production app which has pretty nasty deep routes.

**Comment by davismj** [comment]
Although your approach to this problem is right, I'm almost positive this is going to break some stuff in the framework as well as in live applications as this will likely fire the lifecycle callbacks in reverse. I'd need to investigate to confirm.

**Comment by huochunpeng** [comment]
I agree, fundamental change. This needs thorough test. BTW, I need some help to add test coverage against this.

So far, it does not break my apps. My apps have quite complex router config. This is a good sign.

**Comment by huochunpeng** [comment]
From what I can remember, I think I traced lifecycle callbacks.
With this fix, lifecycle callbacks were fired in expected order just like without router (I mean comparing to nest inner component directly in outer component).

Outer bind
Inner bind
Inner attached
Outer attached

Without this fix, when outer and inner were loaded by router, the lifecycle callbacks were not fired in the above sequence.

**Comment by huochunpeng** [comment]
If this does restore the lifecycle callback sequence to intended way, I expect instead of breaking something, this should fix some other open issues.

**Comment by Alexander-Taran** [comment]
can this also fix this: https://github.com/aurelia/router/issues/410 ?

**Comment by huochunpeng** [comment]
@Alexander-Taran well, you can help to fix 👍 . You always look like got more time than others 😄

**Comment by huochunpeng** [comment]
I vaguely remember I tried that one. If I did, the result is negative.

**Comment by Alexander-Taran** [comment]
Well they seemed kinda related.. I was just curious.. Does your PR ensures that parent router is completely initialized before child.. 
so that apis mentioned in the issue behave consitently on deeplink & navigation

And as you can see, I mostly spend my time reading and answering.. (-:
not coding.. somebody has to

**Comment by huochunpeng** [comment]
There are few issues around Redirect and Promise, I produced them. It looks like some edge cases not related to this issue, I didn't spend more time as I don't use Redirect that often and I am lazy.

**Comment by fkleuver** [comment]
If there is a risk of breaking stuff, would it instead be an idea to make this behavior available via an option like `config.options.swapOrder = swapOrder.default | swapOrder.topDown`?

**Comment by huochunpeng** [comment]
Negative, if this one breaks stuff, it means it has bug. Doesn't mean existing one has no bug. We probably should not ask user do you want bug1 or bug2?

**Comment by fkleuver** [comment]
LOL.

I think you're missing the point though. If there was a bug in the implementation from the very start, especially a subtle one like this which can creep into the architecture, then consumers might have built the application in a way that works around it.

Then, if you fix that bug - and your implementation has **no bugs**, then that in itself might break applications as described above.

So some people might actually want to opt-in to the **correct** behavior or have a chance to test/migrate to it without it being the only option. That's just my opinion though.

**Comment by huochunpeng** [comment]
Thx, make sense. Until my fix break something.

**Comment by Alexander-Taran** [comment]
@huochunpeng how about this one?
https://github.com/aurelia/framework/issues/810

**Comment by PWKad** [comment]
Leaving a bug in because it was written early means that everyone who chooses to use the feature is going to run in to an inconsistency that they have to spend hours looking for work arounds for.  If this fixes the issue with layouts and order of what happens it should be merged and released as a "breaking" change.

**Comment by fkleuver** [comment]
Still, wouldn't making this an **option** address the breaking change issue?

**Comment by Alexander-Taran** [comment]
Option should be a well hidden one
I’m against options (-;

Unless it’s old-buggy-behavior-shim-do-not-use.ts

Bumping a major with a clear note
Can stay on the previous one

**Comment by fkleuver** [comment]
So router 2.0 then?

**Comment by Alexander-Taran** [comment]
Seems like it. Can also mark it as pre-release and ask ppl to test it out

**Comment by huochunpeng** [comment]
I would like aurelia has a pre-release practice. Previously there were few bugs in new if-else feature in template-resources due to not tested enough before release, luckily they were addressed in time.

Aurelia is fast moving target. Pre-release can help hardening new features or dangerous fixes like this.

**Pull request closed without merging**
