### PR TITLE
refactor(all): better interfaces, add router event export, more tests

### PR DESCRIPTION
**Pull request by bigopon**

### CODE REVIEW

**Comment by bigopon** [comment]
This is now ready for review.
- refactor to TS
- ensure compat with latest release
- add export `RouterEvent` for better typings/hooks
- include fix #619

**Comment by bigopon** [comment]
For comparison, typings is based on 1.5.0 release (same for 1.6) at https://github.com/aurelia/router/blob/2a8a16622dc162c9bd24028a76420692f2a0882a/dist/aurelia-router.d.ts

**Comment by bigopon** [comment]
The latest commits https://github.com/aurelia/router/pull/632/files/26facc5f83fd7bb48da8e5015efb943e913c21f7..7d3ee63e77d585f7964ea6706163e1cd2dff7691 will export a few critical information related to router event enum and pipeline slot name enum, along with some comments for better understanding & usage

**Comment by EisenbergEffect** [comment]
@bigopon Is this ready?

**Comment by bigopon** [comment]
@EisenbergEffect yes it is ready. Everything has been reverted to internak refactoring instead of aiming for a 2.0 beta. Its a big refactoring so if needed, we can do a RC release

**Comment by EisenbergEffect** [comment]
@bigopon What is the release process for this library now? Just build and release from master? After this next release, will we be able to use the develop branch and align this process with the other updated repos?

**Pull request merged**
