### PR TITLE
fix(router): ensure routes have distinct names

### PR DESCRIPTION
**Pull request by devanp92**
This is in reference to #366.

Router will throw an error if a route with the same name in addRoute

### CODE REVIEW

**Comment by CasiOo** [comment]
Should the check be a part of `function validateRouteConfig()`?
Should the comparison be case insensitive? Different casing is not tested.

**Comment by devanp92** [comment]
@CasiOo 

> Should the check be a part of function validateRouteConfig()?

That is a good point regarding design. I can make that change if necessary.

> Should the comparison be case insensitive? Different casing is not tested.

Interesting point. @EisenbergEffect can you chime in?

**Comment by EisenbergEffect** [comment]
If possible, it's probably better to locate that inside the existing validation method. As far as case sensitivity goes, the recognizer's name lookup is currently case-sensitive.

**Comment by devanp92** [comment]
@EisenbergEffect Thank you. I have updated the code per your comment.

In validateRouteConfig(), I also needed to pass Router's routes since it was not contained in the validateRouteConfig's context.

**Comment by EisenbergEffect** [comment]
Thank you!

**Pull request merged**
