### PR TITLE
fix(router): router is case sensitive by default

### PR DESCRIPTION
**Pull request by tolemac**
Router is case sensitive by default, if you need to set some route as case sensitive you can add `caseSensitive: true` property to the route configuration.

in order to close https://github.com/aurelia/router/issues/271

### CODE REVIEW

**Comment by tolemac** [comment]
Need https://github.com/aurelia/route-recognizer/pull/21 to pass the tests

**Comment by tolemac** [comment]
Ops! I think the commit message and the pull request name is wrong. It should be "router is case *in*sensitive by default".  Like route-recognizer PR...
What can I do to resolve it?

**Comment by EisenbergEffect** [comment]
@bryanrsmith I'd like to get this in with the other related commit, but looks like the CI is broken. Is it just a CI error? or an issue with the PR?

**Comment by bryanrsmith** [comment]
Looks like a problem with the build. I'll try to fix it on my lunch break.

**Comment by EisenbergEffect** [comment]
@tolemac Again, apologies for taking so long on this. It's in for tomorrow's release 😄

**Pull request merged**
