### PR TITLE
fix(router): add navigationStrategy to cloned route config

### PR DESCRIPTION
**Pull request by StrahilKazlachev**
fix for #386

### CODE REVIEW

**Comment by StrahilKazlachev** [comment]
@EisenbergEffect Could someone take a look at this and the related issue?

**Comment by EisenbergEffect** [comment]
I'm on it. Thanks for reminding me.

**Comment by EisenbergEffect** [comment]
Give me a moment and I'll get the patch release out.

**Comment by EisenbergEffect** [comment]
Patch release coming in a minute.

**Comment by EisenbergEffect** [comment]
Ok, patch release is out.

**Comment by StrahilKazlachev** [comment]
Great, thank you :smiley:

**Pull request merged**
