### PR TITLE
feat(router): add nav failed event

### PR DESCRIPTION
**Pull request by tyrsius**
added an event for router navigation failure
Router:Navigation:Failed

should address issue #2

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Currently the Router doesn't have a dependency on the event aggregator. I'm not sure if it should or not just yet. I'm also not sure if it should publish this globally or have its own instance of the AE that it uses. Need to think about it. Any thoughts?

**Comment by tyrsius** [comment]
I don't see why the router should avoid that dependency, but I can see why it might want to use its own instance. Would you imagine that instance being shared as a property on the router?

**Comment by tyrsius** [comment]
I definitely *don't* think the router should use some *other* mechanism to publish events.

**Comment by EisenbergEffect** [comment]
Ok. That sounds fine. I'd like to ask you to expand this PR by implementing all the same events as Durandal's router, where possible. Do you think you could do that? Also, let's use lowercase for the event names. Sounds good?

**Comment by zewa666** [comment]
[Here](https://github.com/aurelia/router/issues/24) is the issue raised for Durandal Router Events. Not sure but we should maybe think to expand it for the new Pipeline stuff. That one could use some nice events as well.

Regarding the way how Events are triggered. Custom Events would be super nice because they are easy to catch in an E2E Environment. Otherwise we maybe need to find a way how to get the EventAggregator into Protractor.

**Comment by tyrsius** [comment]
I can do that, should have it this week sometime

**Comment by EisenbergEffect** [comment]
@tyrsius I'm gong to close this PR for now. When you've added all the events, please go ahead and submit a new PR. Also, be sure to jspm install aurelia-event-aggregator into the router project so that it's dependencies are correctly accounted for. Thanks for working on this!

**Pull request closed without merging**
