### PR TITLE
fix(navigation-plan): Accept parameters in a redirect config

### LINKED ISSUE #607: Possible bug in redirecting routes with parameters
**I'm submitting a bug report**

* **Library Version:**
1.6.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
9.11.1

* **NPM Version:**
6.0.0

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
Up to version 1.5.0 of Aurelia-router I was using this configuration:
```
[
{ route: 'seguridad-seleccionar-usuario-nuevo', redirect: 'seguridad-seleccionar-usuario/true', nav: true, title: 'Nuevo Usuario' },
{ route: 'seguridad-seleccionar-usuario-modificar', redirect: 'seguridad-seleccionar-usuario/false', nav: true, title: 'Modificar Usuario' },
{ name: 'seguridad-seleccionar-usuario', route: 'seguridad-seleccionar-usuario/:nuevo', moduleId: PLATFORM.moduleName('modulos/herramientas/seguridad/seleccionar-usuario/index', 'herramientas'), nav: false, title: 'Modificar Usuario' }
]
```
The idea was that the two first routes redirect to the third with different parameters.

After upgrading to 1.6.1, an exception is thrown indicating that the parameter isn't being passed.

**Expected/desired behavior:**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

### PR DESCRIPTION
**Pull request by davismj**
All of the following will now work:

```
// Redirects 'first' to 'second/0'
{ route: 'first', redirect: 'second/0' }

// Redirects 'first/1' to 'second/1'
{ route: 'first/:foo', redirect: 'second/:foo' }

// Redirects 'first/1/2' to 'second'
{ route: 'first/:foo/:bar', redirect: 'second/:baz' }

{ route: 'second/:id?' }
```

closes #607

### CODE REVIEW

**Comment by davismj** [comment]
@huochunpeng Thoughts?

**Comment by fkleuver** [comment]
We would definitely need some unit tests to verify that everything still works with child routers. Overlooking the child routers (cough - my redirects PR - cough) seems to be the sole reason for the last few breakages.

**Comment by huochunpeng** [comment]
@fkleuver fyi, both #605 and #607 were introduced by #515, not your redirects PR.

**Comment by fkleuver** [comment]
Paired with the other 2 PRs and the tests I'm fairly sure this won't break anything, so looks good to me.

**Pull request merged**
