### PR TITLE
doc(router): add doc comments on public router and router-configuration API

### PR DESCRIPTION
**Pull request by bryanrsmith**
Also cleaned up some type annotations.

### CODE REVIEW

**Comment by bryanrsmith** [comment]
@cmichaelgraham How's this looking so far? I haven't renamed anything yet, but it's a start.

**Comment by cmichaelgraham** [comment]
want me to PR the new doc generator stuff so you can take a look?

**Comment by bryanrsmith** [comment]
Sure!

**Comment by cmichaelgraham** [comment]
PR'd :+1: 

https://github.com/aurelia/router/pull/181

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can you rebase this on master please?

**Comment by bryanrsmith** [comment]
Done. Should be good to merge.

**Pull request merged**
