### PR TITLE
Fix/child redirects

### PR DESCRIPTION
**Pull request by davismj**
closes https://github.com/aurelia/router/issues/619

### CODE REVIEW

**Comment by davismj** [comment]
If this pull request has helped you, please consider supporting my Aurelia development efforts on Patreon at [http://patreon.com/davismj](http://patreon.com/davismj). Thank you!

**Comment by davismj** [comment]
### Support me on Patreon

I hope my work here helps you. If so, please consider backing me on Patreon so I can afford to make more contributions like these. Thank you!

<a href="http://patreon.com/davismj"></a>

**Comment by davismj** [comment]
### Support me on Patreon

I love working to make Aurelia the greatest front-end framework in the world. If you like my work and want to support me in this mission, please consider backing me on Patreon so I can afford to make more contributions like this one. Thank you!

<a href="http://patreon.com/davismj"></a>

**Comment by bigopon** [comment]
This lgtm. It would be nicer if there could be some comment explaining why `childRoute` in params is linked to child recognizer.

**Pull request merged**
