### PR TITLE
fix(router): check if href property in route table exists in refreshN…

### PR DESCRIPTION
**Pull request by steves714**
…avigation

This fixes an issue where href properties in route tables are changed by the router.

### CODE REVIEW

**Comment by bryanrsmith** [comment]
Thanks, @steves714! Looks good to me.

@EisenbergEffect Please verify CLA and merge at your convenience.

**Comment by steves714** [comment]
No problem Bryan. Thank you! And thanks to your team for building an incredibly awesome framework. I'm guiding two large project rewrites at my company using Aurelia. Keep up the great work!

**Comment by EisenbergEffect** [comment]
Thanks for the contribution!

**Comment by steves714** [comment]
You're very welcome Rob, thank you for Aurelia. Outstanding framework!

**Pull request merged**
