### PR TITLE
feat(vm): Specify moduleId at runtime

### PR DESCRIPTION
**Pull request by zewa666**
feat(vm): Specify moduleId at runtime

This adds the possiblity do define a moduleStrategy which may be a
function. If present it will be executed and will rewrite the moduleId
of the given route. See https://github.com/aurelia/router/issues/3

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
I don't know if the timing of this is correct. My understanding is that people want this strategy to execute later, after the route has been matched so that it can dynamically choose the module id based on the actual navigation instruction. Can you investigate moving the strategy invocation logic?

**Comment by zewa666** [comment]
Hmm I've tried at least a dozen places and all seemed too late, as the router already kicked off. The one in this PR seemed to be the only viable one. What would be the benefit of moving it next to the navigation instruction? Could you think of an example information you'd like to pick out of it? Besides that isn't currentInstruction provided by the router always an option?

**Comment by EisenbergEffect** [comment]
Why not call it from here: https://github.com/aurelia/router/blob/master/src/navigation-instruction.js#L2
It's the earliest time you have the instruction obvious. Also, the moduleId wouldn't have been needed yet by the router, if I remember correctly.

**Comment by zewa666** [comment]
I'm pretty sure I tried that, but will give it another shot later this afternoon and see if it works. Which params should be passed to the function?

**Comment by EisenbergEffect** [comment]
Probably just need to pass `this` so that the callback has the instruction. You would need to invoke it at the bottom so that everything was initialized first. It's possible that we also need to add something to the configuration code that prevents moduleId being "inferred" during configuration when it's not present but the strategy property is.

**Comment by EisenbergEffect** [comment]
Implemented a new config property `navigationStrategy`. If present, it will receive the navigation instruction which it can alter in any way, including setting the moduleId. It can also return a promise if it needs to do this asynchronously.

**Comment by kristianmandrup** [comment]
Awesome!!! :)

**Pull request closed without merging**
