### PR TITLE
fix(tsd): define router property in NavigationInstruction

### PR DESCRIPTION
**Pull request by danhowitt**
Ref: https://github.com/aurelia/router/issues/397

Update NavigationInstruction TypeScript definition to define router.

### CODE REVIEW

**Comment by StrahilKazlachev** [comment]
You should exclude the `dist` folder content.

**Comment by danhowitt** [comment]
@EisenbergEffect amended.

**Comment by EisenbergEffect** [comment]
@danhowitt Are you able to sign the CLA? The checks above have a button you can click to sign.

**Comment by EisenbergEffect** [comment]
Thanks @danhowitt ! Apologies for the delay.

**Pull request merged**
