### PR TITLE
Fallback route config

### PR DESCRIPTION
**Pull request by MT-PL-SWF-Dev**
Proposal of solution for enhancement:
https://github.com/aurelia/router/issues/431

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
I'm happy to merge this but with one request. Before we add a new feature, I'd like to have documentation for it. In the docs folder you will find an article on router configuration. Can you add a section there that covers this feature and add that to this PR? If you can do that we can get it in. I just don't want it to go undocumented. Thanks!

**Comment by MT-PL-SWF-Dev** [comment]
Sure, I will do this soon :)

**Comment by MT-PL-SWF-Dev** [comment]
I cannot merge those conflicts, however I think that everything is ready.

**Comment by stsje** [comment]
Wouldn't it be a good idea to implement the feature the same way as `mapUnknownRoutes` http://aurelia.io/hub.html#/doc/article/aurelia/router/latest/router-configuration/6 ?
So we'll have a `mapFallbackRoutes` function.

**Comment by EisenbergEffect** [comment]
If you can submit a PR for that, I think that would be a better way to handle it, yes.

**Pull request merged**
